name: ocare
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #min sung proj dependencies
  fl_chart: ^0.67.0
  #  intl: ^0.19.0
  #  provider: ^6.1.2
  table_calendar: ^3.1.1
  flutter_svg: ^2.0.10+1
  loading_indicator: ^3.1.1
  #  cupertino_icons: ^1.0.6
  http: ^1.2.1
  bubble: ^1.2.1

  fluttertoast: ^8.2.6

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  intl: ^0.19.0

  numberpicker: ^2.1.2
  cupertino_icons: ^1.0.6

  provider: ^6.1.2
  shared_preferences: ^2.2.2

  kakao_flutter_sdk: ^1.9.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.2

  firebase_app_check:
  go_router: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTF/GmarketSansTTFBold.ttf
          weight: 700
        - asset: assets/fonts/GmarketSansTTF/GmarketSansTTFLight.ttf
          weight: 300
        - asset: assets/fonts/GmarketSansTTF/GmarketSansTTFMedium.ttf
          weight: 500

  assets:
    - assets/robot.svg
    - assets/kakao_login_btn/kakao_login_large_wide.png
